# Generated by Django 5.1.4 on 2025-01-15 11:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
