# Generated by Django 5.1.4 on 2025-01-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employerprofile_country_freelancerprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_jobs', to='profiles.employerprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='profiles.employerprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='profiles.freelancerprofile'),
        ),
    ]
