# Generated by Django 5.1.4 on 2025-01-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_job_employer_alter_review_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_specialty',
        ),
        migrations.RenameModel(
            old_name='Specialty',
            new_name='SkillCategory',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.skillcategory')),
            ],
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.skill'),
        ),
    ]
