# Generated by Django 5.1.4 on 2025-01-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20250115_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='past_jobs_links',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_jobs', to='profiles.skill'),
        ),
        migrations.CreateModel(
            name='JobLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_links', to='profiles.freelancerprofile')),
            ],
        ),
    ]
