# Generated by Django 5.1.5 on 2025-01-23 10:06

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='employer',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='staff_id',
            field=models.CharField(default='default_staff_id', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'IT Freelancer'), ('client', 'Client using the services of IT Freelancers')], max_length=20),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_jobs', to='profiles.clientprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='profiles.clientprofile'),
            preserve_default=False,
        ),
    ]
