# Generated by Django 5.1.5 on 2025-01-23 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_employerprofile_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_previous_works', to='profiles.freelancerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='JobLink',
        ),
    ]
