# Generated by Django 5.1.5 on 2025-01-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_previouswork_delete_joblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20),
        ),
    ]
