# Generated by Django 5.1.5 on 2025-01-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_joblink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
