# Generated by Django 5.2.1 on 2025-05-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('', 'Select a project type'), ('Build a website', 'I want to build a website'), ('Redesign website', 'I want to redesign my website'), ('Improve search rankings', 'I need help improving my search rankings'), ('Create a mobile app', 'I want to create a mobile app'), ('Business database', 'I need a database for my business'), ('Promotional video game', 'I want to create a promotional video game'), ('Content writing', 'I need help writing content for my website or blog'), ('Fix website speed', "I want to fix my website's speed or performance"), ('Design website or app', "I need help designing my website or app's look"), ('Project management', 'I need someone to manage my project and keep it on track')], default='', help_text='Select the project type', max_length=50)),
                ('description', models.TextField(help_text='Provide a detailed description of the job')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Specify the project budget', max_digits=10)),
                ('deadline', models.DateField(help_text='Choose the submission deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.clientprofile')),
                ('skills_required', models.ManyToManyField(help_text='Select the required skills for the job', related_name='jobs', to='profiles.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.freelancerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'freelancer')},
            },
        ),
    ]
