# Generated by Django 5.1.4 on 2025-01-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_job_employer_alter_review_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_specialty', models.CharField(max_length=255)),
                ('website_link', models.URLField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_jobs', to='profiles.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reviews', to='profiles.employerprofile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reviews', to='profiles.freelancerprofile')),
            ],
        ),
    ]
