# Generated by Django 5.1.4 on 2025-01-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='required_specialty',
            new_name='required_skill',
        ),
    ]
