# Generated by Django 5.1.4 on 2025-01-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_required_specialty_job_required_skill'),
        ('profiles', '0006_remove_freelancerprofile_past_jobs_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_jobs', to='profiles.skill'),
        ),
    ]
