# Generated by Django 5.1.4 on 2025-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_job_required_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
