# Generated by Django 5.1.5 on 2025-01-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_job_website_link'),
        ('profiles', '0010_remove_employerprofile_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='employer',
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_jobs', to='profiles.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reviews', to='profiles.clientprofile'),
            preserve_default=False,
        ),
    ]
