# Generated by Django 5.1.5 on 2025-01-25 18:26

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_previouswork'),
        ('profiles', '0012_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='project_category',
            field=models.CharField(choices=[('new_website', 'Build a new website'), ('upgrade_website', 'Upgrade my website'), ('redesign_website', 'Redesign my website')], default='new_website', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='project_title',
            field=models.CharField(default='Untitled Project', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.clientprofile'),
        ),
    ]
