# Generated by Django 5.1.5 on 2025-01-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.job'),
        ),
    ]
