# Generated by Django 5.1.5 on 2025-01-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_message_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='job',
        ),
    ]
