# Generated by Django 5.1.4 on 2025-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stripe_price_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
