# Generated by Django 5.2.1 on 2025-05-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Message Subject')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read?')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is Important?')),
                ('is_reply', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='jobs.application', verbose_name='Related Application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Message Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Message Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'indexes': [models.Index(fields=['sender'], name='user_messag_sender__f6b30a_idx'), models.Index(fields=['recipient'], name='user_messag_recipie_b993b0_idx'), models.Index(fields=['is_read'], name='user_messag_is_read_2f3fb8_idx'), models.Index(fields=['is_important'], name='user_messag_is_impo_18dec9_idx')],
            },
        ),
    ]
